// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiZOs7aGRb8OjRQ9SyfutjencKylSDV-E',
    appId: '1:997704612092:web:0de4e4fbf7779c5c41bf79',
    messagingSenderId: '997704612092',
    projectId: 'fruits-hub-e625e',
    authDomain: 'fruits-hub-e625e.firebaseapp.com',
    storageBucket: 'fruits-hub-e625e.firebasestorage.app',
    measurementId: 'G-TQ63V5LS7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlfe0POxnmNsRTNJEly5JNpBwOKHxJ7Bs',
    appId: '1:997704612092:android:8448c152ebd73bfa41bf79',
    messagingSenderId: '997704612092',
    projectId: 'fruits-hub-e625e',
    storageBucket: 'fruits-hub-e625e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjYMICp-w-GrkcmabEtudgnGJRwfdamVM',
    appId: '1:997704612092:ios:aaa813a2e393130641bf79',
    messagingSenderId: '997704612092',
    projectId: 'fruits-hub-e625e',
    storageBucket: 'fruits-hub-e625e.firebasestorage.app',
    androidClientId: '997704612092-aodt4dspdj70v5p53g6lnaciftuhj9b8.apps.googleusercontent.com',
    iosClientId: '997704612092-vi7ls43ejo1b5kice0psf25h3imkbjvc.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjYMICp-w-GrkcmabEtudgnGJRwfdamVM',
    appId: '1:997704612092:ios:aaa813a2e393130641bf79',
    messagingSenderId: '997704612092',
    projectId: 'fruits-hub-e625e',
    storageBucket: 'fruits-hub-e625e.firebasestorage.app',
    androidClientId: '997704612092-aodt4dspdj70v5p53g6lnaciftuhj9b8.apps.googleusercontent.com',
    iosClientId: '997704612092-vi7ls43ejo1b5kice0psf25h3imkbjvc.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiZOs7aGRb8OjRQ9SyfutjencKylSDV-E',
    appId: '1:997704612092:web:81da525bcb59740141bf79',
    messagingSenderId: '997704612092',
    projectId: 'fruits-hub-e625e',
    authDomain: 'fruits-hub-e625e.firebaseapp.com',
    storageBucket: 'fruits-hub-e625e.firebasestorage.app',
    measurementId: 'G-BEKLST8DT2',
  );
}
